pipeline {
    agent any


    stages {
        stage('Checkout du code') {
            steps {
                git branch: 'main', url: 'https://github.com/fatou0409/terraform_fil_rouge.git'
            }
        }

        stage('Initialisation de Terraform') {
            steps {
                bat 'terraform init'
            }
        }

        stage('Plan Terraform') {
            steps {
                bat 'terraform plan'
            }
        }

        stage('Application de Terraform') {
            steps {
                bat 'terraform apply -auto-approve'
            }
        }
    }
}
